# Generated by Django 3.1.6 on 2021-02-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='order',
        ),
    ]
